development:
  S3_KEY: AKIAITE6PM52LRSDYSUQ
  S3_SECRET: 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
  S3_BUCKET_NAME: pianocoapp

production:
  S3_KEY: AKIAITE6PM52LRSDYSUQ
  S3_SECRET: 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
  S3_BUCKET_NAME: pianocoapp